---
title: "tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE
)
```

```{r setup}
library(hw3zyx)
```

```{r}
X <- c(151, 174, 138, 186, 128, 136, 179, 163, 152, 131)
Y <- c(63, 81, 56, 91, 47, 57, 76, 72, 62, 48)
data<-data.frame(Y,X)
linear_model(Y~X, data)
```

```{r}
x <- cbind(mtcars$disp, mtcars$drat)
y <- mtcars$mpg
linear_model(y~x, mtcars)
```


```{r}
lm1 <- linear_model(Y~X, data)
list1 <- as.data.frame(lm1[[1]])
fit<-lm(Y~X)
sfit <- summary(fit)
compare_list1 <- as.data.frame(sfit$coefficients)
all.equal(list1[,1],round(compare_list1[,1],4)) # estimated coefficients
all.equal(list1[,2],round(compare_list1[,2],4)) # std.error
all.equal(list1[,3],round(compare_list1[,3],4)) # t statistics
all.equal(list1[,4],round(compare_list1[,4],4)) # p-values from t statistics

list2 <- as.data.frame(lm1[[2]])
compare_list2 <- as.data.frame(sfit$fstatistic)
all.equal(as.numeric(list2[,1]),round(compare_list2[1,],4)) # F statistics

list3 <- as.data.frame(lm1[[3]])
compare_list3 <- cbind(as.data.frame(sfit$r.squared),as.data.frame(sfit$adj.r.squared))
compare_list3 <- cbind(as.data.frame(sfit$sigma), compare_list3)
all.equal(list3[,1],round(compare_list3[,1],4)) # sigma
all.equal(list3[,2],round(compare_list3[,2],4)) # R-squared
all.equal(list3[,3],round(compare_list3[,3],4)) # adjusted R-squared

```
