# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_yx <- function(y, x) {
    .Call('_hw3zyx_cov_yx', PACKAGE = 'hw3zyx', y, x)
}

